# Excel file definitions
# Sheet names for inshore logs

last.yr <- 2026

list.sheet.names.inshore <- list(Y1994 = "INSHORE LOG", Y1995 = "Inshore Data", Y1996 = "data",
                                 Y1997 = "LOGS", Y1998 = "LOG", Y1999 = "DATA",
                                 Y2000 = "DATA", Y2001 = "LOGS", Y2002 = "LOGS",
                                 Y2003 = "Logs", Y2004 = "DATA", Y2005 = "LOGS",
                                 Y2006 = "LOGS", Y2007 = "log", Y2008 = "LOG",
                                 Y2009 = "LOGS", Y2010 = "LOGS", Y2011 = "LOGS",
                                 Y2012 = "LOGS", Y2013 = "LOGS", Y2014 = "LOGS",
                                 Y2015 = "LOGS", Y2016 = "LOGS", Y2017 = "LOGS",
                                 Y2018 = "LOGS", Y2019 = "INSHORE LOGS", Y2021 = "INSHORE LOGS",
                                 Y2022 = "MomCalf Logs 2022 postQC",
                                 Y2023 = "PiedrasBlancasCalfProductionDat",
                                 Y2024 = "MOTHER-CALF LOG 2024",
                                 Y2025 = "MOTHER-CALF LOG 2025",
                                 Y2026 = "MOTHER-CALF LOG 2026")

# Sheet names for offshore logs. Starting 2017, offshore logs were eliminated.
list.sheet.names.offshore <- list(Y1994 = NULL, Y1995 = "Offshore Data", Y1996 = "Sheet1",
                                  Y1997 = "LOGS", Y1998 = "LOGS", Y1999 = "DATA",
                                  Y2000 = "LOGS", Y2001 = "LOGS", Y2002 = "LOG",
                                  Y2003 = "logs", Y2004 = "DATA", Y2005 = "LOGS",
                                  Y2006 = "LOGS", Y2007 = "log", Y2008 = "LOGS",
                                  Y2009 = "LOGS", Y2010 = "LOGS", Y2011 = "LOGS",
                                  Y2012 = "LOGS", Y2013 = "LOGS", Y2014 = "LOGS",
                                  Y2015 = "LOGS", Y2016 = NULL)

# Column types for inshore logs. Some years contain more columns (typically one) with
# no identifier, which return "New Name" when the file is read.
list.col.types.inshore <- list(Y1994 = c("date", "numeric", "text", "numeric", "text",
                                         "text", "numeric", "text", "text"),
                               Y1995 = c("date", "numeric", "text", "numeric", "text", 
                                         "text", "numeric", "numeric", "text", "text", 
                                         "text", "text", "text", "text", "text", "text"),
                               Y1996 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "numeric", "text", "text", 
                                         "text", "text", "text"),
                               Y1997 = c("date", "numeric", "text", "numeric", "numeric", 
                                         "numeric", "text", "text", "text", 
                                         "text", "numeric", "text", "text", 
                                         "text"),
                               Y1998 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "numeric", "text", "text", "text", 
                                         "text", "text"),
                               Y1999 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "numeric", "text", "text", "text",
                                         "text", "text", "text"),
                               Y2000 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text",
                                         "text", "text"),
                               Y2001 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text",
                                         "text", "text"),
                               Y2002 =  c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text", "text", "text",
                                          "text", "text"),
                               Y2003 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text",
                                         "text", "text"),
                               Y2004 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text",
                                         "text", "text"),
                               Y2005 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text"),
                               Y2006 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2007 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text", "text"),
                               Y2008 = c("date", "numeric", "text", "numeric", "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", "text", "text", "text"),
                               Y2009 = c("date", "numeric", "text", "numeric", "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", "text", "text", "text"),
                               Y2010 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2011 =  c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text", "text", "text", 
                                          "text", "text", "text"),
                               Y2012 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2013 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2014 =  c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text", "text", "text", 
                                          "text", "text", "text"),
                               Y2015 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2016 = c("date", "numeric", "text", "numeric", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text"),
                               Y2017 = c("date", "numeric", "text", "text", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text", "text",
                                         "text", "text"),
                               Y2018 =  c("numeric", "date", "numeric", "text", "text", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text", "text", "text", 
                                          "text", "text", "text", "text",
                                          "text", "text", "text", "text"),
                               Y2019 =  c("date", "numeric", "numeric", "text", "text", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text", "text", "text", 
                                          "text", "text", "text", "text",
                                          "text", "text", "text"),
                               Y2021 = c("date", "numeric", "numeric", "text", "text", 
                                         "text", "text", "numeric", "numeric", 
                                         "text", "text", "text", "text", 
                                         "text", "text", "text", "text",
                                         "text", "text", "text", "text", "text"),
                               Y2022 = c("date", "numeric", "numeric", "text", "text", 
                                         "text", "text", "numeric", "numeric", "text", 
                                         "text", "text", "text", "numeric", "text", 
                                         "text", "text", "text"),
                               Y2023 = c("date", "numeric", "numeric", "text", "text",
                                         "text", "text","text", "numeric", "text", "text", 
                                         "text", "text", "text", "text", "text", 
                                         "text", "text"),
                               Y2024 = c("date", "numeric", "numeric", "text", "text",
                                         "text", "text","text", "text", "text", "numeric", 
                                         "text", "text", "text", "text", "text", 
                                         "text", "text", "text", "text"),
                               Y2025 = c("date", "numeric", "text", "text",
                                         "text", "text", "numeric", 
                                         "text", "text", "text", "text"),
                               Y2026 = c("date", "numeric", "text", "text",
                                         "text", "text", "numeric", 
                                         "text", "text", "text", "text"))

# Column types for offshore logs. Some years contain more columns (typically one) with
# no identifier, which return "New Name" when the file is read. No offshore files starting
# in 2017.
list.col.types.offshore <- list(Y1994 = c("date", "numeric", "text", "numeric", "text",
                                          "text", "numeric", "numeric", "text", "text"),
                                Y1995 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "numeric", "text", "numeric", "text"),
                                Y1996 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "numeric", "text",  "text"),
                                Y1997 = c("date", "numeric", "text", "numeric", 
                                          "numeric", "text", "text", "numeric", 
                                          "text", "text",  "numeric", "text"),
                                Y1998 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y1999 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2000 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text"),
                                Y2001 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "text", "text",  "text", "text"),
                                Y2002 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2003 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "text", "text",  "text", "text"),
                                Y2004 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2005 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2006 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "text", "text",  "text", "text"),
                                Y2007 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2008 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2009 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2010 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2011 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "text", "text",  "text", "text"),
                                Y2012 =  c("date", "numeric", "text", "numeric", 
                                           "text", "text", "numeric", "numeric", 
                                           "text", "text",  "text", "text"),
                                Y2013 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2014 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2015 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"),
                                Y2016 = c("date", "numeric", "text", "numeric", 
                                          "text", "text", "numeric", "numeric", 
                                          "text", "text",  "text", "text"))

# Column names that are extracted. These are not all the column names in each Excel spreadsheet.
# These are the column names from each Excel spreadsheet that were extracted to be used. 
list.col.names.inshore <- list(Y1994 = c("Date", "Event", "Time", "Obs. Code", "Sea State",
                                         "Vis. IN", "Cow  / Calf"),
                               Y1995 = c("Date",	"Event Code",	"Time",	"Observer Code",	
                                         "Sea State",	"Vis In",	"C/C Pairs"),
                               Y1996 = c("DATE",	"EVENT CODE",	"TIME", "OBS.",	
                                         "SEA STATE",	"VIS (IN/OUT)",	"C/C"),
                               Y1997 = c("DATE",	"EVENT",	"TIME", "OBSER", 
                                         "SEA STATE", "VIS I/O", "C/C"),
                               Y1998 = c("Date",	"Event Code",	"Time",	"Obs",
                                         "Vis (I/O)", "Sea State",	"c/c"	),
                               Y1999 = c("Date",	"Event Code",	"Time", 	"Obs. Code",
                                         "Vis", "Sea State", "C/C"),
                               Y2000 = c("DATE",	"EVENT",	"TIME",	"OBS.",	"VIS (IN/OUT)",	"SEA STATE",	"C/C"),
                               Y2001 = c("DATE",	"EVENT",	"TIME",	"OBS.", "VIS I/O",	"SEA ST",	"C/C"	),
                               Y2002 = c("DATE",	"EVENT",	"TIME", 	"OBS", "VIS (I/O)",	"SS",	"C/C"),
                               Y2003 = c("DATE",	"EVENT",	"TIME", 	"OBS", "VIS (I/O)",	"SS",	"C/C"),
                               Y2004 = c("DATE",	"EVENT",	"TIME", 	"OBS", "VIS (I/O)",	"SS",	"C/C"),
                               Y2005 = c("DATE",	"EVENT",	"TIME", 	"OBS", "VIS (I/O)",	"SS",	"C/C"),
                               Y2006 =  c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2007 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2008 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2009 =  c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2010 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2011 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2012 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2013 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C"),
                               Y2014 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2015 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2016 =  c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2017 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2018 = c("DATE",	"EVENT", 	"TIME",	"OBS#", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2019 = c("DATE",	"EVENT", 	"TIME",	"OBS #", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2021 = c("DATE",	"EVENT", 	"TIME",	"OBS #", "VIS IN",	"SEA ST",	"C/C", "IN/OFF"),
                               Y2022 = c("DATE", 	"EVENT", 	"TIME",	"OBS #", "VIS IN", "SEA ST", "M/C", "LOCATION (IN/OFF)"),
                               Y2023 = c("DATE", "EVENT", "TIME", "OBS #", "SEA ST", "VIS IN", "M/C", "LOCATION (IN/OFF)"),
                               Y2024 = c("DATE", "EVENT", "TIME", "OBS #", "SEA STATE INSHORE", "VIS INSHORE OFF", "M/C", "LOCATION (IN/OFF)"),
                               Y2025 = c("Date", "Event Code", "Time", "Obs.1", "Sea State", "Vis", "M/C", 
                                         "Location (Inshore/Offshore of PB Rocks)", "Time at Rocks", "Time Out", "Notes"),
                               Y2026 = c("Date", "Event Code", "Time", "Obs.1", "Sea State", "Vis", "M/C", 
                                         "Location (Inshore/Offshore of PB Rocks)", "Time at Rocks", "Time Out", "Notes")
)
#for 2026 - deleted on/off event code and obs.2

# Same for offfshore spreadsheets
list.col.names.offshore <- list(Y1994 = c("Date", "Event", "Time", "Obs.", "Sea State",
                                          "Vis. Code", "Cow/Calf"),
                                Y1995 = c("Date",	"Event",	"Time",	"OBS.", 
                                          "Sea", "Vis.", 	"Cow/Calf"),
                                Y1996 = c("DATE",	"EVENT CODE",	"TIME", 	"OBS",
                                          "SEA ST.", "VIS",	"C/C"),
                                Y1997 = c("DATE",	"EVENT CODE",	"TIME", "OBS",
                                          "S STATE", "VIS", "COW/CA"),
                                Y1998 = c("Date",	"Event Code",	"Time",	"Obs",	
                                          "Vis",	"SeaState",	"c/c"),
                                Y1999 = c("Date",	"Event Code",	"Time",	"Observer",	
                                          "Vis. Code",	"Sea State",	"C/C"),
                                Y2000 = c("DATE",	"EVENT",	"TIME",	"OBS.",
                                          "VIS CODE",	"SEA STATE",	"C/C"),
                                Y2001 =  c("DATE",	"EVENT",	"TIME",	"OBS",
                                           "VIS",	"SEA STATE",	"C/C"),
                                Y2002 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SS",	"C/C"),
                                Y2003 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SS",	"C/C"),
                                Y2004 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SS",	"C/C"),
                                Y2005 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SS",	"C/C"),
                                Y2006 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2007 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2008 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2009 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2010 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2011 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2012 =  c("DATE", "EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2013 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2014 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2015 = c("DATE",	"EVENT",	"TIME",	"OBS", "VIS",	"SEA ST",	"C/C"),
                                Y2016 = c("DATE",	"EVENT",	"TIME",	"OBS",	
                                          "VIS",	"SEA ST",	"C/C"))
